import type { PlayerID } from "./Game";

const VASSAL_PREFIX = "vassal-";
const VASSAL_NAME_SUFFIX = "'s Vassal";

/**
 * Vassals use a deterministic ID that permanently records their owner.
 * The capital unit ID is always the final numeric segment, so owner IDs may
 * themselves contain hyphens without making the relationship ambiguous.
 */
export function makeVassalPlayerID(
  ownerID: PlayerID,
  capitalUnitID: number,
): PlayerID {
  return `${VASSAL_PREFIX}${ownerID}-${capitalUnitID}`;
}

/** Returns the owning player's ID, or null when the player is not a vassal. */
export function vassalOwnerIDFromPlayerID(
  playerID: PlayerID,
): PlayerID | null {
  if (!playerID.startsWith(VASSAL_PREFIX)) return null;

  const body = playerID.slice(VASSAL_PREFIX.length);
  const lastDash = body.lastIndexOf("-");
  if (lastDash <= 0) return null;

  const capitalID = body.slice(lastDash + 1);
  if (!/^\d+$/.test(capitalID)) return null;

  const ownerID = body.slice(0, lastDash);
  return ownerID.length > 0 ? ownerID : null;
}

export function isVassalPlayerID(playerID: PlayerID): boolean {
  return vassalOwnerIDFromPlayerID(playerID) !== null;
}

export function makeVassalDisplayName(ownerName: string): string {
  return `${ownerName}${VASSAL_NAME_SUFFIX}`;
}

/**
 * Vassal names are generated by makeVassalDisplayName. This lets lightweight
 * client actions display the owner name without needing a second player lookup.
 */
export function vassalOwnerNameFromDisplayName(name: string): string | null {
  if (!name.endsWith(VASSAL_NAME_SUFFIX)) return null;
  const ownerName = name.slice(0, -VASSAL_NAME_SUFFIX.length);
  return ownerName.length > 0 ? ownerName : null;
}
