import type { Game, Player, PlayerID } from "./Game";

const VASSAL_PREFIX = "vassal-";
const VASSAL_NAME_SUFFIX = "'s Vassal";

/**
 * Vassals use a deterministic ID that permanently records their owner.
 * The capital unit ID is always the final numeric segment, so owner IDs may
 * themselves contain hyphens without making the relationship ambiguous.
 */
export function makeVassalPlayerID(
  ownerID: PlayerID,
  capitalUnitID: number,
): PlayerID {
  return `${VASSAL_PREFIX}${ownerID}-${capitalUnitID}`;
}

/** Returns the owning player's ID, or null when the player is not a vassal. */
export function vassalOwnerIDFromPlayerID(
  playerID: PlayerID,
): PlayerID | null {
  if (!playerID.startsWith(VASSAL_PREFIX)) return null;

  const body = playerID.slice(VASSAL_PREFIX.length);
  const lastDash = body.lastIndexOf("-");
  if (lastDash <= 0) return null;

  const capitalID = body.slice(lastDash + 1);
  if (!/^\d+$/.test(capitalID)) return null;

  const ownerID = body.slice(0, lastDash);
  return ownerID.length > 0 ? ownerID : null;
}

export function isVassalPlayerID(playerID: PlayerID): boolean {
  return vassalOwnerIDFromPlayerID(playerID) !== null;
}

/**
 * Resolve the player whose diplomacy governs this realm. Normal players and
 * nations govern themselves; a vassal is governed by its recorded owner.
 */
export function vassalDiplomaticPrincipal(
  game: Pick<Game, "hasPlayer" | "player">,
  player: Player,
): Player {
  const ownerID = vassalOwnerIDFromPlayerID(player.id());
  if (ownerID === null || !game.hasPlayer(ownerID)) return player;
  return game.player(ownerID);
}

/**
 * Friendship for combat/diplomacy purposes, including vassal ownership.
 *
 * Direct friendship is checked first so team/alliance state still behaves
 * normally. If either side is a vassal, their owner is then used as the
 * diplomatic principal. This is intentionally used by attack and transport
 * execution as well as vassal AI, so an owner's new ally is protected even
 * during the short tick before the explicit mirrored vassal alliance appears.
 */
export function areDiplomaticallyFriendly(
  game: Pick<Game, "hasPlayer" | "player">,
  first: Player,
  second: Player,
): boolean {
  if (first.isFriendly(second)) return true;

  const firstPrincipal = vassalDiplomaticPrincipal(game, first);
  const secondPrincipal = vassalDiplomaticPrincipal(game, second);
  return (
    firstPrincipal === secondPrincipal ||
    firstPrincipal.isFriendly(secondPrincipal)
  );
}

export function makeVassalDisplayName(ownerName: string): string {
  return `${ownerName}${VASSAL_NAME_SUFFIX}`;
}

/**
 * Vassal names are generated by makeVassalDisplayName. This lets lightweight
 * client actions display the owner name without needing a second player lookup.
 */
export function vassalOwnerNameFromDisplayName(name: string): string | null {
  if (!name.endsWith(VASSAL_NAME_SUFFIX)) return null;
  const ownerName = name.slice(0, -VASSAL_NAME_SUFFIX.length);
  return ownerName.length > 0 ? ownerName : null;
}
